"""add Department

Revision ID: 884eb86134d2
Revises: 1d5d27d9952e
Create Date: 2024-08-23 10:06:10.353476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884eb86134d2'
down_revision = '1d5d27d9952e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
